name: talk-demos
channels:
  - conda-forge
dependencies:
  - python==3.10
  - dask==2023.4.0
  - distributed==2023.4.0
  - numpy==1.24.2
  - pandas==2.0.0
  - coiled
  - pyarrow==11.0.0
  - ipykernel==6.21.2
  - dask-labextension==6.1.0
  - jupyterlab==3.6
  - s3fs==2023.4.0
  - python-graphviz==0.20.1 
  - bokeh==2.4.3